### ISSUE TITLE
Questions about Pseudo-label generation.

### ISSUE THREAD

**Issue by LandDreamer** [lyumengyao/blad#5]
Hi! Interesting work!
I have a few questions about "Pseudo-label generation." I've noticed that you set a high threshold to obtain objects for training in classification and regression tasks. However, I'm curious about how you handle the real objects whose confidence falls below the threshold. Do you mark them as backgrounds or ignore their loss? If you choose to mark them as backgrounds, do you take into account the errors introduced by these incorrectly labeled objects?

**Comment by lyumengyao** [comment]
Hi LandDreamer, 
While setting a high threshold to ensure the training stability has been a simple and common practice for pseudo-label training, the low-recall of PLs, as you identified, would lead to objects mistakenly identified as background and harm the performance. 
On the one hand, we have discussed in the paper that this problem is less likely to happen in our active sparse training given the complimentary nature of it. We further re-weighted those PLs in loss computation (See https://github.com/lyumengyao/blad/blob/master/acdet/models/mixed_teacher.py#L414) to alleviate the problem, so that unsupervised images in the mixed-sup setting can benefit from it.
Here, for an active detection task, I did not introduce or try more sophisticated strategies for simplicity and generality. Yet a more advanced pseudo-training method could further improve the label efficiency. Thank you for the discussion!
